sudo: false
language: python
python:
- 2.7
install:
- pip install tox "setuptools>=28.2"
script:
- tox
branches:
  except:
  - skeleton
deploy:
  provider: pypi
  server: https://upload.pypi.org/legacy/
  on:
    tags: true
    all_branches: true
    python: 2.7
  user: jaraco
  distributions: dists
  skip_upload_docs: true
  password:
    secure: P0GnA9t0EnvJgoC00IQFMKuKC2yi7IoMoTeUVbVIevDNNcaLCPLwMlfS+q4QIqDKAQVBN9vTuUj4bu/XVErG00hyM8M58ei78nVb8DYzqCFRMTnKETZH3L45cqeAGewoouQXvsKT+dbYdIglxzgdYALUfSFdjT34cmDTawDuHfNMgce2NzFIcuGsPFo81+J7Pq4kqrc1gs6PLn+EtMPh4CPJ4Ww0jeYLrIzV75CSj31QapIQ5QuDM5zGB1/tsyuJTpahYSNZJZeQv04jgUIIxN3U89pGbhzNmSWoOXow924mDqFkpjjkBeJFkPd4g20rR9dp3iFm7kZtXZ3QuLDfTW3cNY9rAnKxl/wbubK7gdeK2LkairWkVbr6AMCI8xkmi2eHlGd+2gwFQG7MY58EqOIkFEEuo2n6wPIdcjF8eMybZ1LKhso1Fm5oD7HdWjzkxSceG2ICbrQ9WUmeUAuBPvEeiomPOZho7j/BcGpFpFoxCuD2h5ZPFbfaRq3rTDXumwdGZp190U5bWKbFZc1SeGaI5rPEkzjV3zkcaHyU4MrE3Tirc9ekWAU7IZxn8rot3QNLERRlQ+Oa/MJJukYZKipowzOh4ghCf+Ey3hw6CV0KlKbwqKG+LXvPf1YOcuGYbHsjaRVwnGJHBLvhKeUMiNbS10R4WUA3Gqz4VCiZO9A=
